name: Build ImageMagick
on:
  push:
    branches:
      - main
    paths:
      - 'svc/cmd/dev/imagemagick/**'
      - '.github/workflows/build-imagemagick.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'svc/cmd/dev/imagemagick/**'
      - '.github/workflows/build-imagemagick.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create tag
        run: |
          COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          TAG=ghcr.io/a-company-jp/imagemagick:latest
          echo "TAGS=$TAG" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        id: docker-auth
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.TAGS }}
          file: ./svc/cmd/dev/imagemagick/Dockerfile
          context: ./
