name: GoTestFirebaseEmulator
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - '**.go'
      - '.github/**'
jobs:
  go-test-with-firebase-emulator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/a-company-jp/imagemagick
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: go mod download
      - name: Install firebase-emulator
        run: npm install -g firebase-tools
      - name: Run Firebase Emulator
        run: |
          firebase setup:emulators:database
          firebase emulators:start --only database &
      - name: 'Waiting for the emulator to start up'
        run: sleep 20
      - name: Run tests
        env:
          FIREBASE_DATABASE_EMULATOR_HOST: localhost:9000
          ENV_LOCATION: ${{ vars.GITHUB_WORKSPACE }}/pkg/setting/files/setting.testing.yaml
        run: go test -p=1 -race -coverprofile=coverage.txt -covermode=atomic ./... #gosetup
